AllCops:
  TargetRubyVersion: 2.6

Style/StringLiterals:
  Enabled: true

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/VariableNumber:
  EnforcedStyle: snake_case
